config/routes.rb
Rails.application.routes.draw do
  resources :trainers do
    resources :pokemons, only: [:create]
  end
  resources :pokemons, only: :destroy

  resources :restaurants, only: [:index, :show] do
    resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :trainer
  validates :name, :image_url, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, length: { minimum: 10 }
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :name, :banner_url, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  has_many :pokemons, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def create
    @trainer = Trainer.find(params[:trainer_id])
    @pokemon = Pokemon.new(pokemon_params)
    # raise
    @pokemon.trainer = @trainer
    if @pokemon.save
      redirect_to trainer_path(@trainer)
    else
      render 'trainers/show', status: :unprocessable_entity
    end
  end

  def destroy
    # 1. find
    @pokemon = Pokemon.find(params[:id])
    # 2. destroy
    @pokemon.destroy
    # 3. redirect
    redirect_to trainer_path(@pokemon.trainer)
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :image_url)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant) }
        format.json # will look for a create.json.jbuilder
      else
        format.html { render 'restaurants/show', status: :unprocessable_entity }
        format.json  # will look for a create.json.jbuilder
      end
    end

  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: %i[ show edit update destroy ]

  # GET /trainers
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  def show
    # @trainer = Trainer.find(params[:id]) #=> before_action

    @pokemon = Pokemon.new
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  def create
    @trainer = Trainer.new(trainer_params)

    if @trainer.save
      redirect_to @trainer, notice: "Trainer was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /trainers/1
  def update
    if @trainer.update(trainer_params)
      redirect_to @trainer, notice: "Trainer was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /trainers/1
  def destroy
    @trainer.destroy
    redirect_to trainers_url, notice: "Trainer was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trainer_params
      params.require(:trainer).permit(:name, :banner_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainersAndPokemons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_review.html.erb
<p><%= review.content %></p>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>

  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
  </ul>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %> <small><%= @restaurant.address %></small></h1>



  <h2><%= pluralize @restaurant.reviews.size, "review" %></h2>

  <div data-controller='insert-in-list' data-insert-in-list-position-value="beforeend">
      <div class="items" data-insert-in-list-target="items">
        <% if @restaurant.reviews.blank? %>
          Be the first to leave a review for <%= @restaurant.name %>
        <% else %>
            <% @restaurant.reviews.each do |review| %>
              <%= render 'review', review: review  %>
            <% end %>
        <% end %>
      </div>
    <%= render 'reviews/form', restaurant: @restaurant, review: @review %>
  </div>




  <%= link_to "Back to all restaurants", restaurants_path %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([restaurant, review],
                    data: {
                      insert_in_list_target: "form",
                      action: "submit->insert-in-list#send"
                    }) do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/trainers/_form.html.erb
<%= form_with(model: trainer) do |form| %>
  <% if trainer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
        <% trainer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :banner_url, style: "display: block" %>
    <%= form.text_field :banner_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trainers/_trainer.html.erb
<div id="<%= dom_id trainer %>">
  <p>
    <strong>Name:</strong>
    <%= trainer.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= trainer.banner_url %>
  </p>

</div>

app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render "form", trainer: @trainer %>

<br>

<div>
  <%= link_to "Show this trainer", @trainer %> |
  <%= link_to "Back to trainers", trainers_path %>
</div>

app/views/trainers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trainers</h1>

<div id="trainers">
  <% @trainers.each do |trainer| %>
    <%= render trainer %>
    <p>
      <%= link_to "Show this trainer", trainer %>
    </p>
  <% end %>
</div>

<%= link_to "New trainer", new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New trainer</h1>

<%= render "form", trainer: @trainer %>

<br>

<div>
  <%= link_to "Back to trainers", trainers_path %>
</div>

app/views/trainers/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @trainer.banner_url %>);">
  <div class="container">
    <h1><%= @trainer.name %></h1>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <div class="cards mb-3">
        <% @trainer.pokemons.each do |pokemon| %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= pokemon.image_url %>)">
            <%= pokemon.name %>
            <%= link_to '+', pokemon_path(pokemon), data: { turbo_method: :delete, turbo_confirm: "Release #{pokemon.name}?"}, class: 'card__remove-link' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <h4>Add a Pokemon</h4>
      <%= simple_form_for([@trainer, @pokemon]) do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>



<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Edit this trainer", edit_trainer_path(@trainer) %> |
  <%= link_to "Back to trainers", trainers_path %>

  <%= button_to "Destroy this trainer", @trainer, method: :delete %>
</div>